### ISSUE TITLE
Evaluate Environment Options

### ISSUE THREAD

**Issue by bregySilvan** [bregySilvan/TabSolution#1]
## Description
TabSolution just started to get one of the worlds leading software companys. For beginning, we need to setup our Environment. It is common that everyone uses the same software. 
Investigate in finding the best tools for our company when developping with typescript, javascript, nodejs and maybe angular.

- [x]  an IDE for programming (VsCode, Netbeans...)
- [x]  when IDE is chosen, watch out for nice to have extensions (intellisense, autoimport etc.)
- [x]  a package manager (npm, yarn ...)
- [x]  some other tool than Github for handling workflow?

**Comment by Christian-Seematter** [comment]
- [x] Make sure everybody can work with git

**Comment by olinator98** [comment]
Just visit the following link: 
https://jaxenter.de/typescript-einfuehrung-ides-63892

**Comment by olinator98** [comment]
There are a lot of IDEs available for programming with Typescript. 
The most common are: 
- VS Code (Not installed) 
- VS Express or Community
- Netbeans
- Eclipse

There are also a few more, but they aren't very popular

**Comment by Christian-Seematter** [comment]
We've discussed the workspace options in the daily standup last time. @olinator98 You can finalize your results in here.

- [ ] Make sure everybody has their work environment setup.

After the two remaining todo's are complete this issue can be closed.
