### ISSUE TITLE
start build API

### ISSUE THREAD

**Issue by bregySilvan** [bregySilvan/TabSolution#11]
## Description
After a conversation with @TobiasMaru we decided to focus on building a survey tool. Since we need an API anyway, we can go on building.

- [ ] design first core API together with test team
- [ ] implement first core API

Here is a guess of the top of my head, a first API could look like: 

- Tabsolution/auth/login
  params: { name, pw }
  returns:  { accessToken, error? }

- Tabsolution/auth/keepAlive
  params: { accessToken }
  returns:  { accessToken, error? }

- Tabsolution/auth/logout
  params: { accessToken }
  returns: { }

- Tabsolution /survey/addSubject
  params: { subject, accessToken }
  returns: { error? }

- Tabsolution/survey/deleteSubject
  params: { subjId, accessToken }
  returns: { error? }

- Tabsolution/survey/listSubjects
  params: { accessToken }
  returns: { error? }

- Tabsolution/survey/addChildSubject
  params: { parent, child, accessToken }
  returns: { error? }

- Tabsolution/survey/deleteChild
  params: { parent, child, accessToken }
  returns: { error? }

### Info
A subject is some kind of JSON data which is used as base Object. We could use Subject to represent a whole survey, a question, an answer or just any information we wanna display.
Please think about this idea.
Ask me if the provided Idea's make no sense.

**Comment by Christian-Seematter** [comment]
Closing due to the new spec. Good work and explanation!
