### ISSUE TITLE
Clientside GET-request for /title

### ISSUE THREAD

**Issue by SvenHutter** [bregySilvan/TabSolution#13]
## Get-Request title

made to get title from json fetched from server 

- [ ] learn some angular
- [ ] create get request /title/id

##  evtl. Get-Request boards

made to get all values from json fetched from server

- [ ] create get request /board/id

**Comment by olinator98** [comment]
I'm currently working on this issue. Currently, I can get the json from the server. The only remaining problem is an error with the parsing on the clientside. 
@SvenHutter You don't need to work further on this problem, because it's nearly solved.
