### ISSUE TITLE
Server: GET

### ISSUE THREAD

**Issue by JoelPfammatter98** [bregySilvan/TabSolution#20]
All are GET requests

send the data to the client
- [x] /title/id --> "Title1"
- [x] /board/id --> all data from the id in an object {...}
- [x] /data --> all data from the json file in objects in an array [{...},{...},{...}]

in branch: server

**Comment by Christian-Seematter** [comment]
@TheScorpio13 Since you say "in branch server"; Is this the task and you will commit it there, or does your description mean that this is already done?

Are these all GET requests?

You can link to the rest Interface documentation to give your issue context.
