### ISSUE TITLE
No 'Access-Control-Allow-Origin' header in Angular 2 app

### ISSUE THREAD

**Issue by olinator98** [bregySilvan/TabSolution#22]
@TheScorpio13 
When I want to connect me to your server, an error message is displayed in the browser-console. 
You must define the clients which are able to connect to your server. I've solved this error provisory. Please visit this link: 
https://stackoverflow.com/questions/36002493/no-access-control-allow-origin-header-in-angular-2-app
In my case, it was the localhost which need the access to the server.

**Comment by Christian-Seematter** [comment]
This is part of security with HTTP, you can open this up to not encounter any issues during development, but document that this needs to be changed for a production environment.
