### ISSUE TITLE
Save Data in JSON File

### ISSUE THREAD

**Issue by JoelPfammatter98** [bregySilvan/TabSolution#30]
Function Call:
save(Id, Title, AnzahlFolgen, Rating)
z.B.:
save("ID4", "Kono Subarashii", "20", "10")

With that function the data will be saved in the File daten.json

in Branch save-Data-to-json

**Comment by Christian-Seematter** [comment]
Great work!

Tip: Start the branches with the ID as per the standard so they are easier to find. Also AnzahlFolgen and Rating don't need to be Strings.
