### ISSUE TITLE
Interface redeclaration

### ISSUE THREAD

**Issue by olinator98** [bregySilvan/TabSolution#35]
In case of the main goal of our project has the description: 
- title
- description
- image
we decided to take the same in our interface.

interface IBoard {
  title: string;
  description;
  imageURL;
}

@noulyn @bregySilvan  @TobiasMaru  @TheScorpio13 
You can see the implementation of the new interface, including the new version of the server, in my branch client.

**Comment by bregySilvan** [comment]
@olinator98 @TheScorpio13 
I merged #27. Including the new server version from @olinator98.

**Comment by olinator98** [comment]
@bregySilvan I think you merged the old version of the server in the master branch. I've created my PR including the Client and the server. Please review it.

**Comment by Christian-Seematter** [comment]
Shouldn't the update of the interface definition happen in https://github.com/bregySilvan/TabSolution/issues/28? Or was that done already? Is this issue actually to update the server accordingly?

@olinator98 Link to the PR you want to have reviewed so there won't be a mistake.

**Comment by olinator98** [comment]
@Christian-Seematter Yes, I will update #28 directly. In this case, this issue can be closed.
