### ISSUE TITLE
Agility research

### ISSUE THREAD

**Issue by SvenHutter** [bregySilvan/TabSolution#6]
Doing some research about agility strategies

To-Do List:
  - [x] what
  - [x] how
  - [x] why

**Comment by Christian-Seematter** [comment]
Additional systems to consider
- [ ] Extreme Programming
- [x] Kanban
- [ ] Lean Development

**Comment by bregySilvan** [comment]
@SvenHutter 
I think it would be a nice thing if we had some template for writing PR(pull request) and commit title/messages. A first idea is just to add the Issue Number at the front of the title. Feel free to specifiy a first guess as you do your first PR resp. commit.

**Comment by Christian-Seematter** [comment]
Decided to do a modified version of Scrum for now. The process will be further developed as we go along.

**Comment by Christian-Seematter** [comment]
@SvenHutter Feel free to close or extend this issue.

**Comment by Christian-Seematter** [comment]
@SvenHutter Can this be closed?

**Comment by SvenHutter** [comment]
@Christian-Seematter yes
