### ISSUE TITLE
Angular Prototype

### ISSUE THREAD

**Issue by bregySilvan** [bregySilvan/TabSolution#7]
## Description
TabSolution needs to find out which frameworks to use in combination with TypeScript. 

- [ ] setup helloworld in Typescript and Angular
- [ ] add ui wich prints some userlist
- [ ] add functionality for filtering users

**Comment by Christian-Seematter** [comment]
- [ ] Consider that you might split this up into a separate repository during this project
- [ ] Investigate how to best send and receive rest API calls in Angular.

You can use the package `json-server` to spawn a simple server that will return JSON data to feed some dummy information before the projet's API is ready and running.

**Comment by bregySilvan** [comment]
@TheScorpio13 
Pls go on with this task.

**Comment by JoelPfammatter98** [comment]
Sry I don't know what to do. Can you pls explain what you mean?

**Comment by bregySilvan** [comment]
@TheScorpio13 
I last time started to set up a small "Hello World" program in angular 2. Since I helped Lars with building the API I did not go on with the angular 2 example. You should now set up some Angular 2 example program. We assigned this task to you because you weren't there when discussing the API and we wanted you to have some work until next meet up.
Have a look at the board to see who does what now.

**Comment by JoelPfammatter98** [comment]
Which board?

**Comment by Christian-Seematter** [comment]
@TheScorpio13 The board here on github.

**Comment by bregySilvan** [comment]
@TheScorpio13 
Download 'Zenhub' extension for chrome. It's a graphical board for Github which can be accessed via a newly added tab on Github: 

![image](https://user-images.githubusercontent.com/31403441/36300989-a27b1df6-1303-11e8-8bbd-ffa242273b8b.png)

**Comment by JoelPfammatter98** [comment]
nice ty
